#pragma once

// I2C pins (ESP32 defaults)
#define SDA_PIN 21
#define SCL_PIN 22

// Sampling — normal rate
#define SAMPLE_RATE_HZ      100
#define SAMPLE_INTERVAL_MS  (1000 / SAMPLE_RATE_HZ)

// Burst mode — triggered on anomaly, reverts after BURST_DURATION_MS
#define BURST_INTERVAL_MS   5      // 200 Hz
#define BURST_DURATION_MS   2000   // 2 seconds of high-rate capture

// Serial
#define SERIAL_BAUD 115200

// MPU6050 ranges
#define ACCEL_RANGE MPU6050_RANGE_4_G
#define GYRO_RANGE  MPU6050_RANGE_500_DEG

// Onboard LED (GPIO 2 on most ESP32 dev boards)
#define LED_PIN 2

// Set to 0 for Phase 1 data-collection CSV output.
// Set to 1 for Phase 3 on-device TFLite Micro inference.
// Requires model_data.h and model_meta.h generated by ml/convert_tflite.py.
#define INFERENCE_MODE 0

// Set to 1 to also run the Phase 2.5 fault-type classifier whenever an
// anomaly is flagged (adds "fault":"<type>" to the JSON output). Only takes
// effect when INFERENCE_MODE is 1. Requires classifier_data.h and
// classifier_meta.h generated by ml/convert_tflite.py after training with
// ml/train_classifier.py.
#define CLASSIFIER_ENABLED 0
